version: '3'
services:
  discovery:
    image: murfzw/kwetter-discovery-service
    container_name: discovery-server
    ports:
      - 1111:80
    volumes:
      - discovery-data:/tmp
    restart: always

  account-service:
    image: murfzw/kwetter-account-service
    container_name: account-service
    ports:
      - 8081:80
    volumes:
      - account-service-data:/tmp
    depends_on:
      - mongo
      - discovery
    restart: always

  kweet-service:
    image: murfzw/kwetter-kweet-service
    container_name: kweet-service
    ports:
      - 8082:80
    volumes:
      - kweet-service-data:/tmp
    depends_on:
      - mongo
      - discovery
    restart: always
  web:
    image: murfzw/kwetter-web
    container_name: kwetter-web
    ports:
      - 8080:80
    volumes:
      - web-data:/tmp
    depends_on:
      - account-service
      - kweet-service
    restart: always
  
  mongo:
    image: mongo:3.7
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  discovery-data:
  account-service-data:
  kweet-service-data:
  web-data:
  mongo-data: