version: '3'
services:
  discovery:
    image: com.zwolsman.kwetter/discovery-server
    container_name: discovery-server
    ports:
    - 1111:80
    volumes:
    - discovery-data:/tmp
    restart: always
  account-service:
    image: com.zwolsman.kwetter/account-service
    container_name: account-service
    ports:
      - 8081:80
    volumes:
    - account-service-data:/tmp
    restart: always
  mongo:
    image: mongo:3.7
    container_name: mongodb-container
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db


volumes:
  discovery-data:
  account-service-data:
  mongo-data: