version: '3'
services:
  discovery:
    image: com.zwolsman.kwetter/discovery-server
    container_name: discovery-server
    ports:
    - 1111:80
    volumes:
    - discovery-data:/tmp
    restart: always

volumes:
  discovery-data: