spring:
  application:
     name: account-service
  data:
    mongodb:
      database: kwetter
      host: mongo

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery/eureka/
