spring:
  application:
     name: kweet-service
  data:
    mongodb:
      database: kwetter
      #host: mongo

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery/eureka/
    enabled: false