# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kwetter-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for kwetter-ios
  pod 'Kingfisher', '~> 4.0'

end
